import type { AuthUser } from "./auth";

const esc = (value: string): string => value.replace(/[&<>]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[char] ?? char));
const userLabel = (user: AuthUser | null): string => user?.nickname ? esc(user.nickname) : user ? `USER #${user.id}` : "GUEST";

export const render9GridPage = (user: AuthUser | null): Response => {
  const html = `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>9Grid — 9 Grid Survival</title>
<style>:root{color-scheme:dark;font-family:ui-monospace,SFMono-Regular,Consolas,monospace;background:#080b0d;color:#d7e0e5}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:#080b0d;padding:18px}.app{max-width:1180px;margin:auto;border:1px solid #40515a;background:#0b1013;padding:18px}.top{display:flex;justify-content:space-between;gap:12px;border-bottom:1px solid #40515a;padding-bottom:12px}.muted{color:#83939c}.brand{font-weight:800;letter-spacing:2px}.status{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.stat{border:1px solid #33434b;padding:8px 12px;background:#0e1519}.label{font-size:11px;color:#83939c}.value{font-size:18px;margin-top:3px}.detail{font-size:10px;color:#83939c;margin-top:3px}.layout{display:grid;grid-template-columns:minmax(300px,1fr) minmax(300px,1fr);gap:18px}.panel{border:1px solid #33434b;background:#0d1317;padding:14px}.panel h2{font-size:13px;margin:0 0 12px;color:#aebdc5}.board{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;max-width:510px;margin:auto}.slot,.card{border:1px solid #52636c;background:#10191e;color:#d7e0e5;cursor:pointer}.slot{aspect-ratio:1;display:flex;flex-direction:column;align-items:center;justify-content:center}.slot.empty{border-style:dashed;color:#4c5a61}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.card{padding:10px;min-height:92px;text-align:left}.card.selected{outline:2px solid #d7e0e5}.tag{display:inline-block;margin-top:7px;padding:3px 5px;border:1px solid #45555d;font-size:11px}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}button{font:inherit;color:#d7e0e5;background:#111a1e;border:1px solid #52636c;padding:9px 12px;cursor:pointer}button:disabled{opacity:.35;cursor:not-allowed}.log{height:185px;overflow:auto;border:1px solid #26353c;background:#080d10;padding:9px;font-size:12px;line-height:1.6}.synergy{min-height:70px;margin-top:12px}.synergy-line{display:inline-block;margin:4px 6px 0 0;padding:4px 7px;border:1px solid #45555d;font-size:11px}.monster-info{margin-bottom:12px;padding:8px 10px;border:1px solid #33434b}.danger{color:#ff9f9f}.hint{font-size:12px;color:#87979f;margin-top:10px;line-height:1.5}@media(max-width:760px){body{padding:8px}.app{padding:10px}.layout{grid-template-columns:1fr}.cards{grid-template-columns:1fr}.top{flex-direction:column}}</style></head>
<body><main class="app"><header class="top"><div><div class="brand">9GRID // 9 GRID SURVIVAL</div><div class="muted">server-authoritative mode</div></div><div class="muted">${userLabel(user)} · <a href="/" style="color:inherit">HOME</a></div></header>
<section class="status"><div class="stat"><div class="label">ROUND</div><div class="value" id="round">-</div></div><div class="stat"><div class="label">TURN</div><div class="value" id="turn">-</div></div><div class="stat"><div class="label">HP</div><div class="value" id="hp">-</div><div class="detail" id="hp-detail">×1 HEALER LV0</div></div><div class="stat"><div class="label">ATK</div><div class="value" id="atk">-</div><div class="detail" id="atk-detail">×1 WARRIOR LV0</div></div><div class="stat"><div class="label">DEF</div><div class="value" id="def">-</div><div class="detail" id="def-detail">×1 TANK LV0</div></div><div class="stat"><div class="label">MANA</div><div class="value" id="mana">-</div><div class="detail" id="mana-detail">×1 MAGE LV0</div></div><div class="stat"><div class="label">SCORE</div><div class="value" id="score">-</div></div><div class="stat"><div class="label">MONSTER</div><div class="value" id="monster">-</div></div><div class="stat"><div class="label">PHASE</div><div class="value" id="phase">-</div></div></section>
<div class="layout"><section class="panel"><h2>BOARD // 3×3</h2><div class="monster-info"><div class="label">MONSTER ATTACK</div><div class="value" id="monster-attack">-</div></div><div class="board" id="board"></div><div class="synergy" id="synergy"></div></section><section class="panel"><h2>CANDIDATES // SERVER STATE</h2><div class="cards" id="cards"></div><div class="actions"><button id="reroll">REROLL CHECKED</button><button id="combat">EXECUTE COMBAT</button><button id="start">NEW RUN</button></div><div class="hint">상태와 게임 규칙은 서버에서 결정됩니다. 브라우저는 카드 선택, 재굴림 대상, 보드 칸 선택만 전송합니다.</div></section></div>
<section class="panel" style="margin-top:18px"><h2>CLIENT LOG</h2><div class="log" id="log"></div></section><div class="hint">AUTH: ${user ? "SESSION" : "GUEST"} · D1 session-backed</div></main>
<script>
let state=null;let selectedCardId=null;let monsterAttack=8;const rerollSet=new Set();const $=(id)=>document.getElementById(id);
function log(text,cls=""){const p=document.createElement("div");p.className=cls;p.textContent="> "+text;$("log").appendChild(p);$("log").scrollTop=$("log").scrollHeight}
async function request(path,options={}){const response=await fetch(path,{credentials:"same-origin",headers:{"Content-Type":"application/json",...(options.headers||{})},...options});let body=null;try{body=await response.json()}catch{}if(!response.ok){throw new Error(body?.error||"Request failed")}if(Number.isFinite(body?.monsterAttack)){monsterAttack=body.monsterAttack}return body}
function synergyLevel(values,key){return Math.min(5,Math.max(0,Number(values[key]||0)))}
function calculateSynergy(board){const races={};const jobs={};const addLine=(cards)=>{if(cards.length!==3||cards.some((card)=>!card))return;const race=cards.every((card)=>card.race===cards[0].race)?cards[0].race:null;const job=cards.every((card)=>card.job===cards[0].job)?cards[0].job:null;if(race!==null)races[race]=Math.min(5,(races[race]||0)+1);if(job!==null)jobs[job]=Math.min(5,(jobs[job]||0)+1)};for(let row=0;row<3;row+=1)addLine(board.slice(row*3,row*3+3));for(let column=0;column<3;column+=1)addLine([board[column],board[column+3],board[column+6]]);return {races,jobs}}
function renderSynergy(synergy){const raceNames=Object.keys(synergy.races);const jobNames=Object.keys(synergy.jobs);const raceText=raceNames.length?raceNames.map((race)=>'<span class="synergy-line">'+race.toUpperCase()+' LV'+synergyLevel(synergy.races,race)+'</span>').join(''):'<span class="muted">RACE: NONE</span>';const jobText=jobNames.length?jobNames.map((job)=>'<span class="synergy-line">'+job.toUpperCase()+' LV'+synergyLevel(synergy.jobs,job)+'</span>').join(''):'<span class="muted">JOB: NONE</span>';$("synergy").innerHTML='<div class="hint">ACTIVE SYNERGY // RACE</div>'+raceText+'<div class="hint">ACTIVE SYNERGY // JOB</div>'+jobText}
function render(){if(!state){$("round").textContent="-";$("turn").textContent="-";$("hp").textContent="-";$("atk").textContent="-";$("def").textContent="-";$("mana").textContent="-";$("score").textContent="-";$("monster").textContent="-";$("monster-attack").textContent="-";$("phase").textContent="NO SESSION";$("board").innerHTML='<div class="muted">NEW RUN을 시작하세요.</div>';$('cards').innerHTML="";$("reroll").disabled=true;$("combat").disabled=true;return}
const r=state.round,p=state.playerStats,synergy=calculateSynergy(state.board);const warriorLevel=synergyLevel(synergy.jobs,"warrior"),tankLevel=synergyLevel(synergy.jobs,"tank"),healerLevel=synergyLevel(synergy.jobs,"healer"),mageLevel=synergyLevel(synergy.jobs,"mage");$("round").textContent=r.round;$("turn").textContent=r.turn+" / 9";$("hp").textContent=r.playerHp+" / "+r.playerMaxHp;$("atk").textContent=p.attack;$("def").textContent=p.defense;$("mana").textContent=p.mana;$("hp-detail").textContent="×"+(healerLevel+1)+" HEALER LV"+healerLevel;$("atk-detail").textContent="×"+(warriorLevel+1)+" WARRIOR LV"+warriorLevel;$("def-detail").textContent="×"+(tankLevel+1)+" TANK LV"+tankLevel;$("mana-detail").textContent="×"+(mageLevel+1)+" MAGE LV"+mageLevel;$("score").textContent=state.maxClearedRound;$("monster").textContent=r.monsterHp+" / "+r.monsterMaxHp;$("monster-attack").textContent=monsterAttack;$("phase").textContent=r.phase.toUpperCase();
$("board").innerHTML=state.board.map((c,i)=>'<button class="slot '+(c?"":"empty")+'" data-slot="'+i+'">'+(c?'<b>'+c.race.toUpperCase()+"</b><span>"+c.job.toUpperCase()+"</span>":"+")+'</button>').join("");document.querySelectorAll("[data-slot]").forEach((b)=>b.onclick=()=>place(Number(b.dataset.slot)));
const cards=r.candidates.cards;$("cards").innerHTML=cards.map((c,i)=>'<button class="card '+(selectedCardId===c.id ? 'selected ' : '')+'" data-card="'+c.id+'"><b>#'+(i+1)+' '+c.race.toUpperCase()+'</b><br><span>'+c.job.toUpperCase()+'</span><br><span class="tag"><input type="checkbox" data-reroll="'+i+'" '+(rerollSet.has(i) ? 'checked' : '')+'> REROLL</span></button>').join('');document.querySelectorAll("[data-card]").forEach((b)=>b.onclick=()=>selectCard(b.dataset.card));document.querySelectorAll("[data-reroll]").forEach((b)=>b.onclick=(e)=>{e.stopPropagation();const i=Number(b.dataset.reroll);b.checked?rerollSet.add(i):rerollSet.delete(i)});
renderSynergy(synergy);$("reroll").disabled=state.gameOver||r.phase!=="reroll";$("combat").disabled=state.gameOver||r.phase!=="combat";$("start").disabled=false}
function setState(next){state=next;selectedCardId=state?.round.candidates.selectedCardId||null;rerollSet.clear();render()}
async function start(){try{const response=await request("/api/games/9grid/session/action",{method:"POST",body:JSON.stringify({type:"start"})});setState(response.state);log("SERVER: new run started")}catch(e){log(e.message,"danger")}}
async function reroll(){const indexes=[...rerollSet];if(!indexes.length){log("REROLL: 체크한 후보가 없습니다.","danger");return}try{setState((await request("/api/games/9grid/session/action",{method:"POST",body:JSON.stringify({type:"reroll",indexes})})).state);log("SERVER: reroll applied")}catch(e){log(e.message,"danger")}}
async function selectCard(cardId){try{setState((await request("/api/games/9grid/session/action",{method:"POST",body:JSON.stringify({type:"select",cardId})})).state)}catch(e){log(e.message,"danger")}}
async function place(boardIndex){if(!selectedCardId){log("PLACE: 먼저 카드를 선택하세요.","danger");return}try{setState((await request("/api/games/9grid/session/action",{method:"POST",body:JSON.stringify({type:"place",boardIndex})})).state);log("SERVER: placement applied")}catch(e){log(e.message,"danger")}}
async function combat(){try{setState((await request("/api/games/9grid/session/action",{method:"POST",body:JSON.stringify({type:"combat"})})).state);log("SERVER: combat resolved")}catch(e){log(e.message,"danger")}}
$("start").onclick=start;$("reroll").onclick=reroll;$("combat").onclick=combat;
async function load(){try{const response=await request("/api/games/9grid/session",{method:"GET"});if(response.state===null){await start();return}setState(response.state)}catch(e){log(e.message,"danger");render()}}
load();
</script></body></html>`;
  return new Response(html,{headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY","Referrer-Policy":"no-referrer"}});
};
