export interface ClickRushRankingUser {
  id: number;
  nickname: string | null;
  profile_image_url: string | null;
}

const escapeHtml = (value: string): string => value.replace(/[&<>"']/g, (character) => ({
  "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
}[character] ?? character));

export const renderClickRushRankingPage = (user: ClickRushRankingUser | null): string => `<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Click Rush Ranking</title>
<style>:root{font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#191919}*{box-sizing:border-box}body{margin:0;background:#f5f6f8}.top{height:64px;background:#fff;border-bottom:1px solid #e7e7e7;display:flex;align-items:center;justify-content:space-between;padding:0 max(16px,calc((100vw - 900px)/2))}.brand{font-weight:900;text-decoration:none}.user{font-size:14px;font-weight:800}main{width:min(94vw,900px);margin:auto;padding:30px 0 60px}.back{color:#666;text-decoration:none;font-size:14px}h1{font-size:clamp(30px,5vw,42px);margin:18px 0 8px;letter-spacing:-.04em}.sub{color:#777}.tabs{display:flex;gap:8px;margin:22px 0 14px}.tab{border:1px solid #ddd;background:#fff;border-radius:10px;padding:10px 15px;font:inherit;font-weight:800;cursor:pointer}.tab.active{background:#191919;color:#fff;border-color:#191919}.panel{background:#fff;border:1px solid #e5e5e5;border-radius:18px;overflow:hidden}.row{display:grid;grid-template-columns:70px 1fr 120px;padding:13px 16px;border-bottom:1px solid #eee;align-items:center}.head{background:#fafafa;color:#777;font-size:12px;font-weight:800}.rank{font-weight:900}.score{text-align:right;font-weight:900}.mine{background:#f6f6f6}.state{padding:20px;text-align:center;color:#777}.actions{margin-top:16px;display:flex;gap:10px}.actions a{padding:10px 14px;background:#fff;border:1px solid #ddd;border-radius:10px;text-decoration:none;font-weight:800}@media(max-width:600px){.row{grid-template-columns:50px 1fr 90px}.top{padding:0 16px}.user{display:none}}</style></head>
<body><header class="top"><a class="brand" href="/">MINI GAME PORTAL</a><span class="user">${user ? escapeHtml(user.nickname || "내 정보") : "게스트"}</span></header>
<main><a class="back" href="/games/click-rush">← Click Rush</a><h1>Click Rush Ranking</h1><p class="sub">플레이 시간별 최고 기록 · 상위 100명</p><div class="tabs"><button class="tab active" data-duration="60">1분</button><button class="tab" data-duration="180">3분</button><button class="tab" data-duration="300">5분</button></div><section class="panel"><div class="row head"><span>순위</span><span>닉네임</span><span class="score">점수</span></div><div id="ranking"><div class="state">랭킹을 불러오는 중...</div></div></section><div id="myRank" class="state"></div><div class="actions"><a href="/games/click-rush">게임으로 돌아가기</a><a href="/">홈으로</a></div></main>
<script>(()=>{const ranking=document.getElementById("ranking"),myRank=document.getElementById("myRank");let duration=60;const tabs=[...document.querySelectorAll(".tab")];const load=async()=>{ranking.innerHTML='<div class="state">랭킹을 불러오는 중...</div>';try{const r=await fetch('/api/games/click-rush/ranking?duration='+duration);const data=await r.json();if(!r.ok)throw new Error(data.error);ranking.innerHTML=(data.ranking||[]).length?(data.ranking.map(row=>'<div class="row"><span class="rank">'+row.rank+'</span><span>'+escapeText(row.nickname)+'</span><span class="score">'+Number(row.score).toLocaleString()+'</span></div>').join('')):'<div class="state">아직 등록된 기록이 없습니다.</div>';loadMine();}catch{ranking.innerHTML='<div class="state">랭킹을 불러오지 못했습니다.</div>';myRank.textContent='';}};const loadMine=async()=>{try{const r=await fetch('/api/games/click-rush/my-rank?duration='+duration);const data=await r.json();if(r.status===401){myRank.textContent='로그인하면 내 순위를 확인할 수 있습니다.';return;}myRank.textContent=data.rank?('내 순위: '+data.rank+'위 · '+Number(data.score).toLocaleString()+'점'):'이 시간대의 내 기록이 없습니다.';}catch{myRank.textContent='내 순위를 불러오지 못했습니다.';}};const escapeText=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));tabs.forEach(tab=>tab.addEventListener('click',()=>{tabs.forEach(t=>t.classList.remove('active'));tab.classList.add('active');duration=Number(tab.dataset.duration);load();}));load();})();</script></body></html>`;
